### ISSUE TITLE
使用技術の変更について

### ISSUE THREAD

**Issue by Mao-75** [Mao-75/Anitrient#69]
# 質問内容・実現したいこと

アニメ提案機能で**gem ruby-openai**を使用して質問と選択肢と回答をchatGPTにしてもらう予定でしたが、
実装が難しくMVPリリースに間に合わない可能性が出てきたので今回は**gem ruby-openai** を使用せず自分で質問と選択肢を用意したものを使用しようと考えています。
このアプリのコアとなる機能なので今から使用技術を変更しても大丈夫でしょうか？

**Comment by Tsuchiya2** [comment]
> 「次に見たいアニメが決まらない…」
質問に答えていくとその人に合ったアニメを提案、
そして「どのアニメをどこまで見たのか」を管理するアプリです。

こちらに対して、`gem ruby-openai を使用せず自分で質問と選択肢を用意したものを使用しようと考えています`とありますが、具体的にはどういった形になるのか詳しく説明していただけますか？

**Comment by Mao-75** [comment]
コメントありがとうございます。

> こちらに対して、gem ruby-openai を使用せず自分で質問と選択肢を用意したものを使用しようと考えていますとありますが、具体的にはどういった形になるのか詳しく説明していただけますか？

質問を３つ、選択肢(ジャンル一覧)を自作し、ユーザーにジャンル名を選択してもらい、自作のデータベースから選択されたジャンルのアニメを表示するという形です。診断機能のようなイメージです。

[質問例]Q.気になるジャンルはどれですか？ など

選択肢
- SF/ファンタジー
- ロボット/メカ
- アクション/バトル
- コメディ/ギャグ　　など

アニメ提案機能部分のみgem ruby-openaiを使用予定だったのでアニメ提案機能部分のみ変更となります。

あと１点伝え忘れたことがあります。
レコメンド機能についてなのですが、「MVPで実装するにはスケジュール的に重いので本リリース時に実装した方が良さそう」とアドバイスをいただいたのでレコメンド機能を本リリース時に実装したいと思います。

**Comment by Tsuchiya2** [comment]
回答ありがとうございます。

> レコメンド機能についてなのですが、「MVPで実装するにはスケジュール的に重いので本リリース時に実装した方が良さそう」とアドバイスをいただいたのでレコメンド機能を本リリース時に実装したいと思います。

こちらは講師からのアドバイスということであっていますでしょうか。

また、最終の確認ですが、`レコメンド機能`・`gem ruby-openaiを使用してchatGPTにアニメ提案機能させる機能`、この2つがMVP機能からの変更で間違いないでしょうか。

**Comment by Mao-75** [comment]
コメントありがとうございます。

> こちらは講師からのアドバイスということであっていますでしょうか。

はい、その通りです。

>また、最終の確認ですが、レコメンド機能・gem ruby-openaiを使用してchatGPTにアニメ提案機能させる機能、この2つがMVP機能からの変更で間違いないでしょうか。

はい、その通りです。
わかりづらくて申し訳ないです。

**Comment by Tsuchiya2** [comment]
変更内容承知しました。
MVPリリースに向けて頑張ってください！
